export interface Language {
  code: string;
  name: string;
}

export const LANGUAGES: Language[] = [
  { code: 'auto', name: 'Detect language' },
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Spanish' },
  { code: 'fr', name: 'French' },
  { code: 'de', name: 'German' },
  { code: 'it', name: 'Italian' },
  { code: 'pt', name: 'Portuguese' },
  { code: 'ru', name: 'Russian' },
  { code: 'ja', name: 'Japanese' },
  { code: 'ko', name: 'Korean' },
  { code: 'zh', name: 'Chinese (Simplified)' },
  { code: 'zh-TW', name: 'Chinese (Traditional)' },
  { code: 'ar', name: 'Arabic' },
  { code: 'hi', name: 'Hindi' },
  { code: 'tr', name: 'Turkish' },
  { code: 'pl', name: 'Polish' },
  { code: 'nl', name: 'Dutch' },
  { code: 'sv', name: 'Swedish' },
  { code: 'da', name: 'Danish' },
  { code: 'fi', name: 'Finnish' },
  { code: 'no', name: 'Norwegian' },
  { code: 'cs', name: 'Czech' },
  { code: 'ro', name: 'Romanian' },
  { code: 'hu', name: 'Hungarian' },
  { code: 'el', name: 'Greek' },
  { code: 'bg', name: 'Bulgarian' },
  { code: 'hr', name: 'Croatian' },
  { code: 'sk', name: 'Slovak' },
  { code: 'sl', name: 'Slovenian' },
  { code: 'sr', name: 'Serbian' },
  { code: 'uk', name: 'Ukrainian' },
  { code: 'be', name: 'Belarusian' },
  { code: 'mk', name: 'Macedonian' },
  { code: 'vi', name: 'Vietnamese' },
  { code: 'th', name: 'Thai' },
  { code: 'id', name: 'Indonesian' },
  { code: 'ms', name: 'Malay' },
  { code: 'tl', name: 'Filipino' },
  { code: 'he', name: 'Hebrew' },
  { code: 'fa', name: 'Persian' },
  { code: 'ur', name: 'Urdu' },
  { code: 'bn', name: 'Bengali' },
  { code: 'ta', name: 'Tamil' },
  { code: 'te', name: 'Telugu' },
  { code: 'ml', name: 'Malayalam' },
  { code: 'kn', name: 'Kannada' },
  { code: 'gu', name: 'Gujarati' },
  { code: 'pa', name: 'Punjabi' },
  { code: 'mr', name: 'Marathi' },
  { code: 'ne', name: 'Nepali' },
  { code: 'si', name: 'Sinhala' },
  { code: 'my', name: 'Myanmar (Burmese)' },
  { code: 'km', name: 'Khmer' },
  { code: 'lo', name: 'Lao' },
  { code: 'ka', name: 'Georgian' },
  { code: 'am', name: 'Amharic' },
  { code: 'sw', name: 'Swahili' },
  { code: 'zu', name: 'Zulu' },
  { code: 'af', name: 'Afrikaans' },
  { code: 'az', name: 'Azerbaijani' },
  { code: 'eu', name: 'Basque' },
  { code: 'ca', name: 'Catalan' },
  { code: 'gl', name: 'Galician' },
  { code: 'is', name: 'Icelandic' },
  { code: 'ga', name: 'Irish' },
  { code: 'lv', name: 'Latvian' },
  { code: 'lt', name: 'Lithuanian' },
  { code: 'mt', name: 'Maltese' },
  { code: 'cy', name: 'Welsh' },
  { code: 'et', name: 'Estonian' },
  { code: 'hy', name: 'Armenian' },
  { code: 'kk', name: 'Kazakh' },
  { code: 'ky', name: 'Kyrgyz' },
  { code: 'mn', name: 'Mongolian' },
  { code: 'uz', name: 'Uzbek' },
  { code: 'tg', name: 'Tajik' },
  { code: 'tk', name: 'Turkmen' },
  { code: 'bs', name: 'Bosnian' },
  { code: 'sq', name: 'Albanian' },
  { code: 'ha', name: 'Hausa' },
  { code: 'yo', name: 'Yoruba' },
  { code: 'ig', name: 'Igbo' },
  { code: 'xh', name: 'Xhosa' },
  { code: 'st', name: 'Sesotho' },
  { code: 'tn', name: 'Tswana' },
  { code: 've', name: 'Venda' },
  { code: 'ts', name: 'Tsonga' },
  { code: 'ss', name: 'Swati' },
  { code: 'nr', name: 'Ndebele (South)' },
  { code: 'nso', name: 'Sepedi' },
  { code: 'eo', name: 'Esperanto' },
  { code: 'co', name: 'Corsican' },
  { code: 'fy', name: 'Frisian' },
  { code: 'gd', name: 'Scots Gaelic' },
  { code: 'br', name: 'Breton' },
  { code: 'lb', name: 'Luxembourgish' },
  { code: 'yi', name: 'Yiddish' },
  { code: 'ht', name: 'Haitian Creole' },
  { code: 'haw', name: 'Hawaiian' },
  { code: 'sm', name: 'Samoan' },
  { code: 'to', name: 'Tongan' },
  { code: 'ty', name: 'Tahitian' },
  { code: 'mi', name: 'Maori' },
  { code: 'fj', name: 'Fijian' },
  { code: 'mg', name: 'Malagasy' },
  { code: 'ny', name: 'Chichewa' },
  { code: 'rw', name: 'Kinyarwanda' },
  { code: 'so', name: 'Somali' },
  { code: 'ti', name: 'Tigrinya' },
  { code: 'om', name: 'Oromo' },
  { code: 'ak', name: 'Akan' },
  { code: 'ee', name: 'Ewe' },
  { code: 'tw', name: 'Twi' },
  { code: 'ln', name: 'Lingala' },
  { code: 'kg', name: 'Kongo' },
  { code: 'lu', name: 'Luba-Katanga' },
  { code: 'sn', name: 'Shona' },
  { code: 'nd', name: 'Ndebele (North)' },
];

export const getLanguageByCode = (code: string): Language | undefined => {
  return LANGUAGES.find(lang => lang.code === code);
};

export const getLanguageName = (code: string): string => {
  const lang = getLanguageByCode(code);
  return lang?.name || code;
};
